# Franccesca

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: build
      displayName: 'Build'
      steps:
      - task: Gradle@3
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: false
          spotBugsAnalysis: false
    
  - stage: SAST
    jobs:
    - job: sast
      displayName: 'SAST'
      steps:
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'Sonarcloud'
          organization: 'devops-franccesca'
          scannerMode: 'MSBuild'
          projectKey: 'DevOps-Franccesca_spring-boot-kubernetes'
          projectName: 'spring-boot-kubernetes'
      - task: Gradle@3
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'sonarqube'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: true
          sqGradlePluginVersionChoice: 'specify'
          sonarQubeGradlePluginVersion: '3.3'
          spotBugsAnalysis: false
